# Generated by Django 3.2.5 on 2021-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='word_seconds',
            field=models.FloatField(blank=True, default=2, null=True),
        ),
    ]
